Repository boostcamp-2020/IssueTracker-32, pull requests merged in 2020-11, with the labels that each got.

#47 [feat] nginx prefix 변경
  server/app.js
Labels: API, BackEnd

#48 [feat] 리액트 앱 빌드를 위한 초기 설정 구현
  .gitignore
  client/.eslintrc
  client/.prettierrc
  client/babel.config.js
  client/build/index.html
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/components/App.js
  client/src/index.js
  client/webpack.config.js
Labels: Develop Setting, FrontEnd, WEEK 2

#49 [FEAT] 로그인 페이지 컴포넌트 및 css 완료
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/index.js
  client/src/pages/App.js
  client/src/pages/LoginPage.js
Labels: FrontEnd, WEEK 2

#51 [FEAT] 웹 라우터 이슈페이지 및 로그인 페이지에 설정
  client/package-lock.json
  client/package.json
  client/src/index.js
  client/src/pages/App.js
  client/src/pages/IssuePage.js
  client/webpack.config.js
Labels: FrontEnd, WEEK 2

#58 [feat] axios 테스트 및 코드 포매팅
  client/babel.config.js
  client/package-lock.json
  client/package.json
  client/src/pages/App.js
  client/src/pages/SocialPage.js
  server/app.js
  server/configs/dbConfig.js
  server/configs/passportConfig.js
  server/models/comment.model.js
  server/models/index.js
  server/models/issue.model.js
  server/models/label.model.js
  server/models/milestone.model.js
  server/models/user.model.js
  server/services/auth.service.js
Labels: BackEnd, FrontEnd, WEEK 2

#59 [feat] axios 인터셉터 구현 및 권한 테스트
  client/src/api/index.js
  client/src/api/interceptor.js
  client/src/pages/App.js
  client/src/pages/IssuePage.js
  client/src/pages/SaveJWTPage.js
  client/src/pages/SocialPage.js
  server/services/auth.service.js
Labels: BackEnd, FrontEnd, WEEK 2, auth, bug

#67 [FEAT] 네비게이션바, Footer 구현
  client/src/components/Common/Footer.js
  client/src/components/Common/NavigationBar.js
  client/src/pages/App.js
Labels: FrontEnd, UI

#68 [feat] : 이슈 페이지 필터링 컨테이너 컴포넌트 및 css 작업
  client/src/components/IssuePage/IssueFilterContainer.js
  client/src/components/IssuePage/IssueListContainer.js
  client/src/pages/IssuePage.js
Labels: FrontEnd, UI

#71 [feat] 목업 데이터 API 구현
  client/mocks/api/issue/GET.json
  client/package-lock.json
  client/package.json
  client/src/api/index.js
  client/src/api/interceptor.js
  client/src/pages/IssuePage.js
  client/webpack.config.js
Labels: FrontEnd

#72 [feat] 이슈 리스트 페이지 컴포넌트 및 css 작업
  client/src/components/IssuePage/IssueFilterContainer.js
  client/src/components/IssuePage/IssueList.js
  client/src/components/IssuePage/IssueListContainer.js
  client/src/components/IssuePage/IssueListHeader.js
  client/src/components/IssuePage/issueItem.js
  client/src/pages/IssuePage.js
Labels: FrontEnd, UI

#74 [feat] issueList 를 서버에 받아서 fetch 후 사용
  client/src/api/index.js
  client/src/api/interceptor.js
  client/src/components/IssuePage/issueItem.js
  client/src/pages/IssuePage.js
Labels: FrontEnd

#75 [feat] jwt 를 이용한 로그인 완료 , 이슈 조회 API , 초기 데이터 시딩, 이슈 조회 컴포넌트 및 css 작업
  client/babel.config.js
  client/mocks/api/issue/GET.json
  client/package-lock.json
  client/package.json
  client/src/api/index.js
  client/src/api/interceptor.js
  client/src/components/Common/Footer.js
  client/src/components/Common/NavigationBar.js
  client/src/components/IssuePage/IssueFilterContainer.js
  client/src/components/IssuePage/IssueList.js
  client/src/components/IssuePage/IssueListContainer.js
  client/src/components/IssuePage/IssueListHeader.js
  client/src/components/IssuePage/issueItem.js
  client/src/pages/App.js
  client/src/pages/IssuePage.js
  client/src/pages/SaveJWTPage.js
  client/webpack.config.js
  server/app.js
  server/configs/dbConfig.js
  server/configs/passportConfig.js
  server/controllers/issue.controller.js
  server/models/comment.model.js
  server/models/index.js
  server/models/issue.model.js
  server/models/label.model.js
  server/models/milestone.model.js
  server/models/user.model.js
  server/package-lock.json
  server/package.json
  server/routes/auth.js
  server/routes/index.js
  server/routes/issue.js
  server/seeder/seeder.js
  server/services/auth.service.js
  server/services/issue.service.js
Labels: API, BackEnd, Develop Setting, FrontEnd, UI, auth

#86 [feat] 글로벌 CSS 로 css reset 적용
  client/src/components/Common/GlobalStyle.js
  client/src/pages/App.js
Labels: FrontEnd

#87 [feat] 시간 , 상태 , 유저 정보 등을 알려주는 subtext 생성 함수
  client/package-lock.json
  client/package.json
  client/src/components/IssuePage/IssueItem.js
Labels: FrontEnd

#88 [feat] 이슈 , 레이블 , 마일스톤 , 트라이앵글 아이콘 추가 및 재사용 가능한 filterButton component 추가
  client/src/components/Common/FilterButton.js
  client/src/components/Common/LabelItem.js
  client/src/components/Common/LabelList.js
  client/src/components/Common/NavigationBar.js
  client/src/components/IssuePage/IssueFilterContainer.js
  client/src/components/IssuePage/IssueItem.js
  client/src/components/IssuePage/IssueListHeader.js
Labels: FrontEnd, UI

#85 [FEAT] 이슈 아이템에 Lable 출력 및 Global 스타일 적용 , 서브 텍스트(시간상태유저정보)생성 함수 완료 , 아이콘 추가
  client/package-lock.json
  client/package.json
  client/src/components/Common/FilterButton.js
  client/src/components/Common/GlobalStyle.js
  client/src/components/Common/LabelItem.js
  client/src/components/Common/LabelList.js
  client/src/components/Common/NavigationBar.js
  client/src/components/IssuePage/IssueFilterContainer.js
  client/src/components/IssuePage/IssueItem.js
  client/src/components/IssuePage/IssueListHeader.js
  client/src/pages/App.js
Labels: FrontEnd, UI

#90 [feat] 배경색에 맞는 폰트 색깔 계산
  client/src/components/Common/LabelItem.js
Labels: FrontEnd, UI

#103 [feat] 커스텀 모달 컴포넌트 작성 및 모달 작업
  client/package-lock.json
  client/package.json
  client/src/components/Common/FilterButton.js
  client/src/components/Common/ModalContainer.js
  client/src/components/Common/ModalItem.js
  client/src/components/Common/ModalList.js
  client/src/components/IssuePage/IssueItem.js
Labels: FrontEnd, UI

#102 [feat] 마일스톤 item 컴포넌트 , 커스텀 모달 컴포넌트 생성 및 모달 연결 작업
  client/package-lock.json
  client/package.json
  client/src/components/Common/FilterButton.js
  client/src/components/Common/LabelItem.js
  client/src/components/Common/MilestoneItem.js
  client/src/components/Common/ModalContainer.js
  client/src/components/Common/ModalItem.js
  client/src/components/Common/ModalList.js
  client/src/components/IssuePage/IssueItem.js
Labels: FrontEnd, UI

#106 [feat] Issue 생성 페이지 구현
  client/src/components/NewIssuePage/CommentForm.js
  client/src/components/NewIssuePage/CommentFormContainer.js
  client/src/components/NewIssuePage/CommentProfileImg.js
  client/src/components/NewIssuePage/Sidebar.js
  client/src/pages/App.js
  client/src/pages/NewIssuePage.js
Labels: FrontEnd, UI

#105 [feat] issue(목록,상세,추가,삭제,수정, filter), milestone(추가,삭제,수정,개수), label(추가,삭제,수정,개수), comment(추가,삭제,수정)
  server/app.js
  server/controllers/comment.controller.js
  server/controllers/issue.controller.js
  server/controllers/label.controller.js
  server/controllers/milestone.controller.js
  server/controllers/user.controller.js
  server/models/index.js
  server/routes/comment.js
  server/routes/index.js
  server/routes/issue.js
  server/routes/label.js
  server/routes/milestone.js
  server/routes/user.js
  server/seeder/seeder.js
  server/services/comment.service.js
  server/services/issue.service.js
  server/services/label.service.js
  server/services/milestone.service.js
  server/services/user.service.js
Labels: API, BackEnd

#108 [feat] FilterContext 생성 및 필터링 요소 조건으로 필터링 string 생성
  client/src/components/IssuePage/IssueFilterContainer.js
  client/src/context/FilterContext.js
  client/src/pages/IssuePage.js
  client/webpack.config.js
Labels: FrontEnd

#107 [feat] 데이터 fetch후 count들 모두 보여주기 및 FilterContext 생성 및 필터링 요소 조건으로 필터링 string 생성
  client/src/api/index.js
  client/src/components/Common/FilterButton.js
  client/src/components/Common/LabelList.js
  client/src/components/Common/MilestoneItem.js
  client/src/components/Common/ModalContainer.js
  client/src/components/Common/ModalList.js
  client/src/components/IssuePage/IssueFilterContainer.js
  client/src/components/IssuePage/IssueItem.js
  client/src/components/IssuePage/IssueList.js
  client/src/components/IssuePage/IssueListContainer.js
  client/src/components/IssuePage/IssueListHeader.js
  client/src/context/FilterContext.js
  client/src/pages/App.js
  client/src/pages/IssuePage.js
  client/src/pages/NewIssuePage.js
  client/webpack.config.js
Labels: FrontEnd, UI

#113 [feat] assignee 필터, 이슈 상세 조회 시 댓글 작성자 정보 포함, moran 설정
  server/app.js
  server/configs/swagger.js
  server/controllers/comment.controller.js
  server/controllers/issue.controller.js
  server/controllers/label.controller.js
  server/controllers/milestone.controller.js
  server/package-lock.json
  server/package.json
  server/routes/comment.js
  server/routes/index.js
  server/routes/issue.js
  server/routes/label.js
  server/routes/milestone.js
  server/seeder/seeder.js
  server/services/issue.service.js
  server/swagger/issue.yaml
  server/swagger/user.yaml
Labels: BackEnd

#114 [feat] FilterContext의 필터링 조건을 이용한 조회와 커스텀 훅을 이용한 코드 refactoring
  client/src/api/index.js
  client/src/components/IssuePage/IssueFilterContainer.js
  client/src/components/IssuePage/IssueListContainer.js
  client/src/components/IssuePage/IssueListHeader.js
  client/src/components/IssuePage/ListHeaderContainer/author/ModalContainer.js
  client/src/components/IssuePage/ListHeaderContainer/author/ModalItem.js
  client/src/context/FilterContext.js
  client/src/hooks/index.js
  client/src/pages/IssuePage.js
Labels: FrontEnd

#117 [feat] updateIssuesData 추가로 계속 이슈 데이터 업데이트
  client/src/components/IssuePage/IssueListContainer.js
Labels: FrontEnd, UI

#118 [feat] 이슈 디테일 페이지 , 새로운 이슈 만들기 페이지 라우팅 연결
  client/src/components/IssuePage/IssueFilterContainer.js
  client/src/components/IssuePage/IssueItem.js
Labels: FrontEnd

#122 [feat] 텍스트 입력시 분석후 스테이트 적용
  client/src/api/index.js
  client/src/components/Common/FilterButton.js
  client/src/components/IssuePage/IssueFilterContainer.js
  client/src/components/IssuePage/IssueItem.js
  client/src/components/IssuePage/ListHeaderContainer/assignee/FilterButton.js
  client/src/components/IssuePage/ListHeaderContainer/assignee/ModalItem.js
  client/src/components/IssuePage/ListHeaderContainer/author/FilterButton.js
  client/src/components/IssuePage/ListHeaderContainer/author/ModalItem.js
  client/src/components/IssuePage/ListHeaderContainer/label/FilterButton.js
  client/src/components/IssuePage/ListHeaderContainer/label/ModalItem.js
  client/src/components/IssuePage/ListHeaderContainer/milestone/FilterButton.js
  client/src/components/IssuePage/ListHeaderContainer/milestone/ModalItem.js
  client/src/context/FilterContext.js
Labels: FrontEnd, UI

#128 [feat] 이슈 페이지에 코멘트 달고 리다이렉트
  client/src/api/index.js
  client/src/components/IssueDetailPage/CommentForm.js
  client/src/components/IssueDetailPage/CommentList.js
  client/src/pages/IssueDetailPage.js
  client/webpack.config.js
Labels: FrontEnd
